package com.smartpg.module.room.model;

import com.smartpg.module.property.model.Property;
import com.smartpg.module.room.enums.RoomStatus;
import com.smartpg.module.room.enums.RoomType;
import jakarta.persistence.*;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;
import org.hibernate.annotations.UuidGenerator;

import java.math.BigDecimal;
import java.time.Instant;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

/**
 * Represents a single physical room inside a Property.
 *
 * <p><b>Think of it like this (real-world analogy):</b>
 * Ek property = ek building (e.g., "Sunrise PG").
 * Ek Room = building ke andar ka ek kamra (e.g., "Room 101").
 * Ek Bed = us kamre mein ek bunk/cot (e.g., "Bed A" in Room 101).
 *
 * <p><b>Why is Room a separate entity from Property?</b>
 * <ul>
 *   <li>A property has many rooms. Rooms are the bookable unit, not the property.</li>
 *   <li>Each room has its own price, type (single/double/triple), floor, and amenities.</li>
 *   <li>Status transitions (AVAILABLE → FULLY_OCCUPIED) happen at the room level.</li>
 *   <li>Tenant search: "Show me DOUBLE rooms under ₹8000" → needs Room, not just Property.</li>
 * </ul>
 *
 * <p><b>Hierarchy:</b>
 * <pre>
 *   Property (Sunrise PG)
 *       └── Room (Room 101 — Double, Floor 1)
 *               ├── Bed (Bed A — OCCUPIED by Rahul)
 *               └── Bed (Bed B — AVAILABLE)
 * </pre>
 *
 * <p><b>Key Business Rules:</b>
 * <ol>
 *   <li>Room's {@code monthlyRent} is the price PER BED (not per room). This simplifies
 *       billing — we always bill per bed in shared accommodations.</li>
 *   <li>Room {@code capacity} must match {@code RoomType}:
 *       SINGLE=1, DOUBLE=2, TRIPLE=3, QUAD=4+. Validated in service layer.</li>
 *   <li>Room cannot be deleted if any of its beds are OCCUPIED or RESERVED.
 *       The service layer enforces this before soft-deleting.</li>
 * </ol>
 *
 * <p><b>Table</b>: {@code rooms}
 */
@Entity
@Table(
    name = "rooms",
    indexes = {
        // Owner views all rooms in a property: WHERE property_id = ?
        @Index(name = "idx_rooms_property_id",        columnList = "property_id"),
        // Tenant search: "Show me AVAILABLE double rooms"
        @Index(name = "idx_rooms_status",             columnList = "status"),
        // Filter by type (SINGLE, DOUBLE, etc.)
        @Index(name = "idx_rooms_type",               columnList = "room_type"),
        // Combined: most common search — available rooms in a property
        @Index(name = "idx_rooms_property_status",    columnList = "property_id, status"),
        // Price range search: "Rooms under ₹8000/month"
        @Index(name = "idx_rooms_monthly_rent",       columnList = "monthly_rent"),
        // Floor-based search (e.g., "ground floor preferred")
        @Index(name = "idx_rooms_floor_number",       columnList = "floor_number")
    }
)
@Getter
@Setter
@NoArgsConstructor
@ToString(exclude = {"property", "beds"})
public class Room {

    // -------------------------------------------------------------------------
    // Primary Key
    // -------------------------------------------------------------------------

    /**
     * Non-sequential UUID primary key.
     * Prevents ID enumeration attacks. A malicious actor can't guess room IDs
     * by incrementing an integer (e.g., they won't find Room 1001 by trying 1000, 1001, 1002).
     * Generated by Hibernate BEFORE the INSERT — so id is never null on a managed entity.
     */
    @Id
    @UuidGenerator
    @Column(name = "id", updatable = false, nullable = false)
    private UUID id;

    // -------------------------------------------------------------------------
    // Parent Property Relationship
    // -------------------------------------------------------------------------

    /**
     * The Property this room belongs to.
     *
     * <p><b>ManyToOne</b>: Many rooms belong to one property. The FK column
     * {@code property_id} lives in this (rooms) table — that's how ManyToOne works.
     *
     * <p><b>FetchType.LAZY</b>: When listing beds for a room, we don't need to load
     * the full property (name, description, owner, photos, amenities...).
     * LAZY prevents that wasteful JOIN on every room fetch.
     *
     * <p><b>updatable = false</b>: A room's parent property can NEVER change once created.
     * You can't "move" Room 101 from Sunrise PG to a different building — business-wise
     * that makes no sense. This constraint lives at the JPA level AND the DB level.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(
        name = "property_id",
        nullable = false,
        updatable = false,
        foreignKey = @ForeignKey(name = "fk_rooms_property_id")
    )
    private Property property;

    // -------------------------------------------------------------------------
    // Room Identity
    // -------------------------------------------------------------------------

    /**
     * Human-readable room identifier set by the owner.
     * Examples: "101", "A2", "Ground Floor West", "Terrace Suite".
     * Unique within the same property (service layer enforces, not DB constraint —
     * because uniqueness is scoped to a property, not globally).
     * Shown to tenants on listing cards and tenancy agreements.
     */
    @Column(name = "room_number", nullable = false, length = 20)
    private String roomNumber;

    /**
     * Floor on which this room is located.
     * 0 = Ground Floor (Indian convention).
     * Negative values = Basement (rare but possible).
     * Used for: tenant preference filters ("I want ground floor"),
     * property layout visualization, and accessibility info.
     */
    @Column(name = "floor_number", nullable = false)
    private Integer floorNumber;

    // -------------------------------------------------------------------------
    // Room Classification
    // -------------------------------------------------------------------------

    /**
     * Sharing arrangement: SINGLE, DOUBLE, TRIPLE, or QUAD.
     * Drives capacity validation: a SINGLE room can only have 1 bed, etc.
     * Critical for tenant search filter ("Show me only single rooms").
     *
     * @see RoomType
     */
    @Enumerated(EnumType.STRING)
    @Column(name = "room_type", nullable = false, length = 20)
    private RoomType roomType;

    /**
     * Maximum number of beds allowed in this room.
     * Must align with roomType: SINGLE=1, DOUBLE=2, TRIPLE=3, QUAD=4+.
     * Validated by RoomService before persisting.
     *
     * <p>Why store it explicitly? Because we need it to:
     * <ol>
     *   <li>Validate bed additions: "Can I add another bed to this room?"</li>
     *   <li>Calculate occupancy rate: occupiedBeds / capacity</li>
     *   <li>Drive FULLY_OCCUPIED auto-transition logic</li>
     * </ol>
     */
    @Column(name = "capacity", nullable = false)
    private Integer capacity;

    // -------------------------------------------------------------------------
    // Pricing
    // -------------------------------------------------------------------------

    /**
     * Monthly rent in Indian Rupees (INR), charged PER BED.
     *
     * <p><b>Why per bed, not per room?</b>
     * In shared PGs, each tenant pays individually. If Room 101 (Double) costs
     * ₹8,000/bed, Rahul pays ₹8,000 and Priya pays ₹8,000 — total room revenue
     * is ₹16,000. Billing at the bed level makes invoice generation trivial.
     *
     * <p><b>Why BigDecimal, not Double/Float?</b>
     * Floating-point types (double, float) have precision issues with decimal arithmetic.
     * Example: 0.1 + 0.2 = 0.30000000000000004 in floating-point math.
     * For money, this is UNACCEPTABLE. BigDecimal gives exact decimal precision.
     * Rule of thumb: ALWAYS use BigDecimal for money in Java.
     *
     * <p>Stored as NUMERIC(10,2) in PostgreSQL → max ₹99,99,999.99 per bed.
     */
    @Column(name = "monthly_rent", nullable = false, precision = 10, scale = 2)
    private BigDecimal monthlyRent;

    // -------------------------------------------------------------------------
    // Room Features & Description
    // -------------------------------------------------------------------------

    /**
     * Owner's description of this specific room.
     * Supplements the property-level description with room-specific details.
     * Example: "Corner room with 2 windows. Great natural light. Attached bathroom."
     * Nullable — owner can add later. Displayed on the room detail view.
     */
    @Column(name = "description", columnDefinition = "TEXT")
    private String description;

    /**
     * Whether this room has an attached bathroom.
     * Critical for tenant preference filtering.
     * A room with an attached bath commands higher rent than a shared-bath room.
     * Defaults to false (shared bathroom is the common PG scenario).
     */
    @Column(name = "has_attached_bathroom", nullable = false)
    private boolean hasAttachedBathroom = false;

    /**
     * Whether this room has an attached balcony or terrace.
     * A nice-to-have that many tenants filter by.
     * Defaults to false.
     */
    @Column(name = "has_balcony", nullable = false)
    private boolean hasBalcony = false;

    /**
     * Whether this room has an air conditioner.
     * AC rooms are typically priced higher. This field drives:
     * <ol>
     *   <li>Tenant filter: "Show me only AC rooms"</li>
     *   <li>Pricing comparisons in admin reports</li>
     * </ol>
     * Defaults to false.
     */
    @Column(name = "has_ac", nullable = false)
    private boolean hasAc = false;

    // -------------------------------------------------------------------------
    // Lifecycle State
    // -------------------------------------------------------------------------

    /**
     * Current availability state of this room.
     *
     * <p>Default: AVAILABLE — a newly created room is ready for beds to be added
     * and (once beds are added) for tenants to book.
     *
     * <p>Auto-transitions:
     * <ul>
     *   <li>Last vacant bed gets booked → system sets FULLY_OCCUPIED</li>
     *   <li>An occupied bed becomes vacant → system sets AVAILABLE</li>
     * </ul>
     * Manual transitions: Owner sets UNDER_MAINTENANCE / INACTIVE.
     *
     * @see RoomStatus
     */
    @Enumerated(EnumType.STRING)
    @Column(name = "status", nullable = false, length = 25)
    private RoomStatus status = RoomStatus.AVAILABLE;

    // -------------------------------------------------------------------------
    // Child Beds Relationship
    // -------------------------------------------------------------------------

    /**
     * All individual beds in this room.
     *
     * <p><b>OneToMany</b>: One room has many beds. The FK {@code room_id} lives in
     * the {@code beds} table (the "many" side always holds the FK).
     *
     * <p><b>CascadeType.ALL</b>: Saving the room cascades to all its beds.
     * No need to separately call bedRepository.save(bed) — it flows through room.save().
     *
     * <p><b>orphanRemoval = true</b>: If a Bed is removed from this list and the room
     * is saved, Hibernate deletes that Bed's row from the DB.
     * This is the correct way to delete a bed — via the parent aggregate.
     *
     * <p><b>FetchType.LAZY</b>: Loading a room's summary doesn't need all its beds.
     * Beds are loaded only when room.getBeds() is called explicitly.
     *
     * <p><b>Initialized to empty ArrayList</b>: So callers can always do
     * {@code room.getBeds().add(bed)} without NullPointerException.
     */
    @OneToMany(mappedBy = "room", cascade = CascadeType.ALL, orphanRemoval = true, fetch = FetchType.LAZY)
    @OrderBy("bedLabel ASC")
    private List<Bed> beds = new ArrayList<>();

    // -------------------------------------------------------------------------
    // Audit Timestamps
    // -------------------------------------------------------------------------

    /**
     * UTC timestamp of when this room was first created.
     * Set ONCE on INSERT via @PrePersist. Never changes.
     * Why Instant? Timezone-agnostic. UTC everywhere, converted at the UI layer.
     */
    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    /**
     * UTC timestamp of the last modification to this room record.
     * Auto-refreshed on every UPDATE via @PreUpdate.
     */
    @Column(name = "updated_at", nullable = false)
    private Instant updatedAt;

    // -------------------------------------------------------------------------
    // Lifecycle Hooks
    // -------------------------------------------------------------------------

    /**
     * Called by Hibernate BEFORE the first INSERT.
     * Guarantees createdAt and updatedAt are always set — even if RoomService
     * forgets to set them. This is your safety net.
     */
    @PrePersist
    protected void onCreate() {
        Instant now = Instant.now();
        this.createdAt = now;
        this.updatedAt = now;
    }

    /**
     * Called by Hibernate BEFORE every UPDATE.
     * Always refreshes updatedAt to the current UTC instant.
     * This is how we know when a room was last modified (e.g., rent was changed).
     */
    @PreUpdate
    protected void onUpdate() {
        this.updatedAt = Instant.now();
    }

    // -------------------------------------------------------------------------
    // Computed / Derived Properties (no DB column — computed in application layer)
    // -------------------------------------------------------------------------

    /**
     * Counts how many beds in this room are currently AVAILABLE.
     * Transient — computed from the in-memory beds list, NOT stored in DB.
     *
     * <p><b>Why @Transient?</b> Because this value is DERIVED from the beds list.
     * Storing it in DB would mean keeping it in sync manually — a classic data
     * consistency bug source. Instead, we compute it on-demand.
     *
     * <p><b>Caveat</b>: This method only works correctly if {@code beds} is loaded
     * (i.e., not lazy-loaded). Always initialize rooms with beds fetched when
     * using this method. In production, prefer a JPQL COUNT query instead.
     */
    @Transient
    public long getAvailableBedCount() {
        return beds.stream()
                .filter(bed -> bed.getStatus() == com.smartpg.module.room.enums.BedStatus.AVAILABLE)
                .count();
    }

    /**
     * Returns true if every bed in this room is occupied.
     * Used by the service layer to auto-transition room status to FULLY_OCCUPIED.
     */
    @Transient
    public boolean isAtCapacity() {
        return beds.stream()
                .noneMatch(bed -> bed.getStatus() == com.smartpg.module.room.enums.BedStatus.AVAILABLE);
    }

    // -------------------------------------------------------------------------
    // equals & hashCode
    // -------------------------------------------------------------------------

    /**
     * Equality based solely on {@code id}.
     *
     * <p><b>Why not @Data or @EqualsAndHashCode?</b>
     * Lombok's @Data uses ALL fields → infinite loop risk with bidirectional JPA
     * relationships (Room ↔ Bed ↔ Room ↔ ...). Plus, two new Room objects
     * (both id=null) would incorrectly be equal.
     * Manual equals/hashCode on id avoids all these issues.
     */
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Room other)) return false;
        return id != null && id.equals(other.id);
    }

    @Override
    public int hashCode() {
        // Fixed constant — intentional. Explained in detail in User entity comments.
        return getClass().hashCode();
    }
}
