-- =============================================================================
-- V1__create_users.sql
-- Smart PG & Rental Management System
-- =============================================================================
-- Purpose  : Create the `users` table — the central identity record for every
--            actor on the platform (SUPER_ADMIN, ADMIN, OWNER, CARETAKER, TENANT).
-- Author   : Smart PG Dev Team
-- Migration: V1 — this MUST run first. All other tables have FKs into `users`.
-- Notes    :
--   • UUID primary keys (gen_random_uuid() or set by Hibernate @UuidGenerator).
--   • Enum columns stored as VARCHAR — never integers (ORDER matters for Flyway).
--   • Two UNIQUE constraints on email + phone (also backed by B-Tree indexes).
--   • Soft-delete pattern: status = 'DELETED', never a physical row removal.
--   • Timestamps stored as TIMESTAMPTZ (timestamp with time zone) — always UTC.
-- =============================================================================


-- -----------------------------------------------------------------------------
-- STEP 1: Create the ENUM types
-- Using CHECK constraints instead of PostgreSQL CREATE TYPE enums so that:
--   (a) Adding a new role/status doesn't require ALTER TYPE (which is DDL and
--       requires a full table lock in older PG versions).
--   (b) Flyway migrations stay additive-only (we just add a new CHECK value).
--   (c) The column remains a plain VARCHAR — fully readable in DB tools.
-- -----------------------------------------------------------------------------


-- -----------------------------------------------------------------------------
-- STEP 2: Create the `users` table
-- -----------------------------------------------------------------------------

CREATE TABLE users (

    -- -------------------------------------------------------------------------
    -- Primary Key
    -- UUID generated by Hibernate @UuidGenerator (set before INSERT).
    -- NOT using SERIAL/BIGINT — non-sequential UUIDs prevent ID enumeration attacks.
    -- updatable = false in JPA mirrors the DB-level immutability of this column.
    -- -------------------------------------------------------------------------
    id              UUID            NOT NULL,

    -- -------------------------------------------------------------------------
    -- Authentication Credentials
    -- email  : Primary login identifier. UNIQUE + NOT NULL.
    --          Enforced at DB level. Service layer additionally lowercases before save.
    -- phone  : Optional secondary login identifier.
    --          Nullable because some users register with email only.
    --          UNIQUE — no two accounts can share a phone number.
    -- password_hash: BCrypt hash (cost ≥ 12). NEVER plaintext.
    --          Length 255: BCrypt output is always 60 chars, but 255 allows
    --          migrating to Argon2 (longer hashes) in the future without schema change.
    -- -------------------------------------------------------------------------
    email           VARCHAR(255)    NOT NULL,
    phone           VARCHAR(15),
    password_hash   VARCHAR(255)    NOT NULL,

    -- -------------------------------------------------------------------------
    -- Role & Status — stored as VARCHAR with CHECK constraints
    -- role  : Determines what the user CAN do (authorization).
    --         Valid values: SUPER_ADMIN, ADMIN, OWNER, CARETAKER, TENANT
    -- status: Determines whether the user CAN act (account lifecycle).
    --         Valid values: ACTIVE, INACTIVE, SUSPENDED, PENDING_VERIFICATION, DELETED
    --         Default: PENDING_VERIFICATION — new registrations start here.
    -- -------------------------------------------------------------------------
    role            VARCHAR(20)     NOT NULL,
    status          VARCHAR(25)     NOT NULL    DEFAULT 'PENDING_VERIFICATION',

    -- -------------------------------------------------------------------------
    -- Verification Flags
    -- email_verified : TRUE after user clicks the email verification link.
    --                  Until TRUE, password resets via email won't work.
    -- phone_verified : TRUE after user submits the correct SMS OTP.
    --                  Until TRUE, phone-based login/notifications are blocked.
    -- Both default to FALSE — a freshly registered user hasn't verified anything yet.
    -- -------------------------------------------------------------------------
    email_verified  BOOLEAN         NOT NULL    DEFAULT FALSE,
    phone_verified  BOOLEAN         NOT NULL    DEFAULT FALSE,

    -- -------------------------------------------------------------------------
    -- Audit Timestamps — all stored as TIMESTAMPTZ (= UTC in PostgreSQL).
    -- created_at : Set once on INSERT by @PrePersist. Never updated.
    -- updated_at : Refreshed on every UPDATE by @PreUpdate.
    -- last_login_at : Nullable — a user who registered but never logged in has
    --                 no last login time. Updated by AuthService.login() on success.
    -- -------------------------------------------------------------------------
    created_at      TIMESTAMPTZ     NOT NULL    DEFAULT NOW(),
    updated_at      TIMESTAMPTZ     NOT NULL    DEFAULT NOW(),
    last_login_at   TIMESTAMPTZ,

    -- -------------------------------------------------------------------------
    -- Primary Key Constraint (named for easy identification in DB tools)
    -- -------------------------------------------------------------------------
    CONSTRAINT pk_users PRIMARY KEY (id),

    -- -------------------------------------------------------------------------
    -- Unique Constraints
    -- Named constraints allow us to catch specific violations in the service:
    --   catch (DataIntegrityViolationException e) {
    --       if (e.getMessage().contains("uk_users_email")) → throw DuplicateEmailException
    --       if (e.getMessage().contains("uk_users_phone")) → throw DuplicatePhoneException
    --   }
    -- -------------------------------------------------------------------------
    CONSTRAINT uk_users_email   UNIQUE (email),
    CONSTRAINT uk_users_phone   UNIQUE (phone),

    -- -------------------------------------------------------------------------
    -- CHECK Constraints on Enum Columns
    -- Prevent garbage data (e.g., role = 'SUPERADMIN' vs 'SUPER_ADMIN') that
    -- JPA validation might miss if a native SQL INSERT is run directly.
    -- -------------------------------------------------------------------------
    CONSTRAINT chk_users_role   CHECK (role   IN ('SUPER_ADMIN', 'ADMIN', 'OWNER', 'CARETAKER', 'TENANT')),
    CONSTRAINT chk_users_status CHECK (status IN ('ACTIVE', 'INACTIVE', 'SUSPENDED', 'PENDING_VERIFICATION', 'DELETED'))

);

-- -----------------------------------------------------------------------------
-- STEP 3: Create Indexes
-- PostgreSQL automatically creates an index for PRIMARY KEY and UNIQUE constraints.
-- These additional indexes are for non-unique query patterns:
-- -----------------------------------------------------------------------------

-- idx_users_role  : Used when filtering users by role.
--   Example query : SELECT * FROM users WHERE role = 'OWNER' → hits this index.
--   Use case      : Admin dashboard "show all owners", "show all pending verifications".
CREATE INDEX idx_users_role ON users (role);

-- idx_users_status: Used when filtering users by lifecycle state.
--   Example query : SELECT * FROM users WHERE status = 'SUSPENDED' → hits this index.
--   Use case      : Admin can quickly list all suspended/deleted accounts.
CREATE INDEX idx_users_status ON users (status);

-- idx_users_last_login_at: Used for inactivity detection.
--   Example query : SELECT * FROM users WHERE last_login_at < NOW() - INTERVAL '90 days'.
--   Use case      : Scheduled job to mark old accounts INACTIVE or send re-engagement emails.
CREATE INDEX idx_users_last_login_at ON users (last_login_at);

-- -----------------------------------------------------------------------------
-- STEP 4: Table and Column Comments
-- These show up in pgAdmin, DBeaver, and any INFORMATION_SCHEMA query.
-- Very useful when a new dev joins the project.
-- -----------------------------------------------------------------------------

COMMENT ON TABLE  users                  IS 'Central identity and authentication record for all platform actors.';
COMMENT ON COLUMN users.id               IS 'UUID primary key. Generated by Hibernate @UuidGenerator before INSERT.';
COMMENT ON COLUMN users.email            IS 'Primary login identifier. Stored lowercase. Globally unique.';
COMMENT ON COLUMN users.phone            IS 'Optional secondary login identifier. Must be globally unique when provided.';
COMMENT ON COLUMN users.password_hash    IS 'BCrypt hash (cost >= 12). NEVER store plaintext here.';
COMMENT ON COLUMN users.role             IS 'User role: SUPER_ADMIN | ADMIN | OWNER | CARETAKER | TENANT';
COMMENT ON COLUMN users.status           IS 'Account lifecycle: ACTIVE | INACTIVE | SUSPENDED | PENDING_VERIFICATION | DELETED';
COMMENT ON COLUMN users.email_verified   IS 'Set to TRUE after user clicks the email verification link.';
COMMENT ON COLUMN users.phone_verified   IS 'Set to TRUE after user completes SMS OTP verification.';
COMMENT ON COLUMN users.created_at       IS 'UTC timestamp of account creation. Immutable.';
COMMENT ON COLUMN users.updated_at       IS 'UTC timestamp of last update. Refreshed on every UPDATE.';
COMMENT ON COLUMN users.last_login_at    IS 'UTC timestamp of most recent successful login. NULL if never logged in.';
