-- =============================================================================
-- V2__create_user_profiles.sql
-- Smart PG & Rental Management System
-- =============================================================================
-- Purpose  : Create the `user_profiles` table — extended personal/KYC data
--            for all registered users.
-- Depends  : V1__create_users.sql (FK → users.id)
-- Author   : Smart PG Dev Team
-- Notes    :
--   • 1:1 relationship with `users`. FK column is `user_id` on THIS table
--     (UserProfile is the owning side in JPA @OneToOne).
--   • Aadhaar & PAN are stored as AES-256 ciphertext in VARCHAR(64).
--     DO NOT add a UNIQUE constraint on aadhaar_number here — ciphertext
--     uniqueness != plaintext uniqueness when IVs differ. Checked in service layer.
--   • ON DELETE CASCADE: if a user row is hard-deleted (should never happen
--     in our soft-delete design, but cascade protects referential integrity).
--   • gender stored as VARCHAR, not a PostgreSQL ENUM — adding 'INTERSEX' or
--     custom options in future requires only a CHECK constraint update.
--   • date_of_birth stored as DATE (not TIMESTAMPTZ) — no time component needed.
-- =============================================================================


-- -----------------------------------------------------------------------------
-- Create the `user_profiles` table
-- -----------------------------------------------------------------------------

CREATE TABLE user_profiles (

    -- -------------------------------------------------------------------------
    -- Primary Key
    -- UUID generated by Hibernate @UuidGenerator before INSERT.
    -- -------------------------------------------------------------------------
    id                  UUID            NOT NULL,

    -- -------------------------------------------------------------------------
    -- Foreign Key → users(id)
    -- UNIQUE on user_id enforces the 1:1 relationship at DB level.
    --   Without UNIQUE: one user could accumulate multiple profile rows.
    --   With UNIQUE   : PostgreSQL rejects a second INSERT with same user_id.
    -- NOT NULL       : every profile row MUST reference a real user.
    -- ON DELETE CASCADE: cascade ensures no orphan profile rows if user is
    --   physically deleted (we never do this, but the DB stays clean).
    -- -------------------------------------------------------------------------
    user_id             UUID            NOT NULL,

    -- -------------------------------------------------------------------------
    -- Basic Identity Fields
    -- All nullable — not required at registration. User fills these in
    -- progressively during onboarding (reducing registration friction).
    -- first_name / last_name: VARCHAR(100) — accommodates long South Asian names.
    -- profile_photo_url: VARCHAR(500) — stores the permanent S3/GCS object URL.
    --   NOT a pre-signed URL (those expire). The object URL is permanent.
    -- -------------------------------------------------------------------------
    first_name          VARCHAR(100),
    last_name           VARCHAR(100),
    profile_photo_url   VARCHAR(500),

    -- -------------------------------------------------------------------------
    -- Personal Details
    -- date_of_birth: DATE type — only year/month/day, no timezone.
    --   Used for age verification (some PGs restrict entry to 18+).
    -- gender: VARCHAR(20) with CHECK constraint.
    --   Valid values kept in application domain, CHECK keeps DB honest.
    -- alternate_phone: A secondary number (e.g., WhatsApp, emergency contact).
    --   Different from the primary phone on `users`. Nullable.
    -- bio: TEXT — no length limit. PostgreSQL TEXT is effectively unlimited.
    --   Used on tenant's public profile when applying to a PG.
    -- -------------------------------------------------------------------------
    date_of_birth       DATE,
    gender              VARCHAR(20),
    alternate_phone     VARCHAR(15),
    bio                 TEXT,

    -- -------------------------------------------------------------------------
    -- KYC Documents (Encrypted at Rest)
    -- aadhaar_number: 12-digit Aadhaar. After AES-256 encryption + Base64,
    --   ciphertext is ~44 chars. VARCHAR(64) gives headroom for padding.
    -- pan_number     : 10-char PAN. After encryption, ~44 chars. Same sizing.
    --
    -- WHY NO UNIQUE CONSTRAINT HERE?
    --   If we used AES-GCM (with random IV per encryption), the same Aadhaar
    --   "123456789012" encrypted twice would produce two DIFFERENT ciphertexts.
    --   A UNIQUE constraint on ciphertext would allow duplicate Aadhaars.
    --   We use AES-ECB/SIV (deterministic mode) to get consistent ciphertext
    --   for the same plaintext, but uniqueness is still enforced at SERVICE layer
    --   via a findByAadhaarNumber check before save.
    -- -------------------------------------------------------------------------
    aadhaar_number      VARCHAR(64),
    pan_number          VARCHAR(64),

    -- -------------------------------------------------------------------------
    -- Audit Timestamps
    -- created_at: Set once on INSERT by @PrePersist. NOT NULL + DEFAULT.
    -- updated_at: Refreshed by @PreUpdate on every change.
    -- -------------------------------------------------------------------------
    created_at          TIMESTAMPTZ     NOT NULL    DEFAULT NOW(),
    updated_at          TIMESTAMPTZ     NOT NULL    DEFAULT NOW(),

    -- -------------------------------------------------------------------------
    -- Constraints
    -- -------------------------------------------------------------------------
    CONSTRAINT pk_user_profiles         PRIMARY KEY (id),

    -- 1:1 enforcement: each user_id can appear only once in this table
    CONSTRAINT uk_user_profiles_user_id UNIQUE (user_id),

    -- Referential integrity: user_id MUST exist in users table
    CONSTRAINT fk_user_profiles_user_id
        FOREIGN KEY (user_id)
        REFERENCES users (id)
        ON DELETE CASCADE,

    -- Gender validation — keep values in sync with the Java entity's comment
    CONSTRAINT chk_user_profiles_gender
        CHECK (gender IS NULL OR gender IN ('MALE', 'FEMALE', 'OTHER', 'PREFER_NOT_TO_SAY'))

);

-- -----------------------------------------------------------------------------
-- Indexes
-- -----------------------------------------------------------------------------

-- idx_user_profiles_user_id:
--   Most common query path: "give me the profile for user X".
--   Used in every GET /api/v1/users/me call.
--   Note: UNIQUE constraint above already creates an index on user_id in
--         PostgreSQL, but naming it explicitly helps with query plan reading.
--   (PostgreSQL actually skips creating a second index for the same column
--    if one already exists — this is a documentation comment + safety net.)
CREATE INDEX idx_user_profiles_user_id ON user_profiles (user_id);

-- idx_user_profiles_last_name:
--   Admin search: "find all users with last name = 'Sharma'".
--   Partial index could be used in future for verified-only searches.
CREATE INDEX idx_user_profiles_last_name ON user_profiles (last_name);

-- -----------------------------------------------------------------------------
-- Comments
-- -----------------------------------------------------------------------------

COMMENT ON TABLE  user_profiles                   IS 'Extended personal, contact, and KYC data for registered users. 1:1 with users table.';
COMMENT ON COLUMN user_profiles.id                IS 'UUID PK — generated by Hibernate before INSERT.';
COMMENT ON COLUMN user_profiles.user_id           IS 'FK to users(id). UNIQUE enforces 1:1 relationship.';
COMMENT ON COLUMN user_profiles.first_name        IS 'Legal first name. Used in emails, receipts, and UI displays.';
COMMENT ON COLUMN user_profiles.last_name         IS 'Legal family/last name.';
COMMENT ON COLUMN user_profiles.profile_photo_url IS 'Permanent S3/GCS object URL. NOT a pre-signed URL.';
COMMENT ON COLUMN user_profiles.date_of_birth     IS 'Date only (no time). Used for age verification.';
COMMENT ON COLUMN user_profiles.gender            IS 'MALE | FEMALE | OTHER | PREFER_NOT_TO_SAY. Nullable.';
COMMENT ON COLUMN user_profiles.alternate_phone   IS 'Secondary contact number. Different from primary phone on users table.';
COMMENT ON COLUMN user_profiles.bio               IS 'Short self-introduction shown on tenant public profile.';
COMMENT ON COLUMN user_profiles.aadhaar_number    IS 'AES-256 encrypted 12-digit Aadhaar. Uniqueness enforced at service layer.';
COMMENT ON COLUMN user_profiles.pan_number        IS 'AES-256 encrypted 10-char PAN. Used for financial compliance.';
COMMENT ON COLUMN user_profiles.created_at        IS 'UTC timestamp of profile creation. Immutable.';
COMMENT ON COLUMN user_profiles.updated_at        IS 'UTC timestamp of last profile update.';
