-- =============================================================================
-- V6__create_properties.sql
-- Smart PG & Rental Management System
-- =============================================================================
-- Purpose  : Create the `properties` table — the core listing entity.
--            Represents every PG / Flat / Hostel / Studio listed by an Owner.
-- Depends  : V1__create_users.sql (FK to `users.id` for owner_id)
-- Notes    :
--   • UUID primary keys — prevents ID enumeration attacks (unlike SERIAL ints).
--   • All enum columns stored as VARCHAR + CHECK constraint (not PostgreSQL ENUM TYPE)
--     so adding a new value = just update the CHECK, no ALTER TYPE needed.
--   • Soft-delete pattern: status = 'DELETED', never a physical row removal.
--     This preserves all tenant history, payment records, and audit logs.
--   • `approved_by` is a raw UUID (not FK) to avoid a JOIN overhead on every
--     property fetch. Admin accountability via application-level lookup only.
--   • Timestamps use TIMESTAMPTZ (timestamp with timezone) = always stored as UTC.
-- =============================================================================


-- -----------------------------------------------------------------------------
-- STEP 1: Create the `properties` table
-- -----------------------------------------------------------------------------

CREATE TABLE properties (

    -- -------------------------------------------------------------------------
    -- Primary Key
    -- Non-sequential UUID generated by Hibernate @UuidGenerator BEFORE the INSERT.
    -- Non-sequential = harder to enumerate (attacker can't guess "property #1001").
    -- -------------------------------------------------------------------------
    id                      UUID            NOT NULL,

    -- -------------------------------------------------------------------------
    -- Owner Reference
    -- FK to users.id. An owner can have many properties.
    -- updatable = false in JPA mirrors this: once set, owner_id never changes.
    -- NOT NULL: every listing must have an owner. Orphaned properties = impossible.
    -- ON DELETE RESTRICT: if someone tries to delete a user who has properties,
    --   the DB blocks it. The application must handle the deactivation workflow first.
    -- -------------------------------------------------------------------------
    owner_id                UUID            NOT NULL,

    -- -------------------------------------------------------------------------
    -- Core Identity
    -- name       : What tenants see in search ("Sunrise PG for Girls"). 255 chars max.
    -- type       : PG | FLAT | HOSTEL | STUDIO — drives filtering in tenant search.
    -- description: Rich text, no length limit (PostgreSQL TEXT). Nullable — owner
    --              can add later. Shows on the listing detail page.
    -- -------------------------------------------------------------------------
    name                    VARCHAR(255)    NOT NULL,
    type                    VARCHAR(20)     NOT NULL,
    description             TEXT,

    -- -------------------------------------------------------------------------
    -- Lifecycle State
    -- status : Controls visibility + editability.
    --   PENDING_APPROVAL: freshly submitted, awaiting admin review.
    --   ACTIVE          : live and visible to tenants.
    --   INACTIVE        : owner temporarily hid it (no active tenancies needed).
    --   REJECTED        : admin rejected it; owner must fix and resubmit.
    --   DELETED         : soft-deleted. Invisible everywhere. Never hard-deleted.
    -- rejection_reason: Admin writes this when rejecting. Owner reads it to know
    --   what to fix. NULL for all states except REJECTED.
    -- -------------------------------------------------------------------------
    status                  VARCHAR(20)     NOT NULL    DEFAULT 'PENDING_APPROVAL',
    rejection_reason        TEXT,

    -- -------------------------------------------------------------------------
    -- Policies
    -- gender_preference: Drives critical tenant filtering.
    --   ANY         : anyone can apply.
    --   MALE_ONLY   : only male-identified tenants.
    --   FEMALE_ONLY : only female-identified tenants.
    --   Enforced at service layer (BookingService rejects mismatches before INSERT).
    -- house_rules: Freeform text. "No smoking. Guests allowed till 10pm." Nullable.
    -- security_deposit_amount: INR amount. Nullable (some owners waive deposit).
    -- is_featured: Admin-only flag. Featured listings appear at top of search.
    --   Owners cannot set this on their own — service layer enforces.
    -- -------------------------------------------------------------------------
    gender_preference       VARCHAR(15)     NOT NULL    DEFAULT 'ANY',
    house_rules             TEXT,
    security_deposit_amount INTEGER,
    is_featured             BOOLEAN         NOT NULL    DEFAULT FALSE,

    -- -------------------------------------------------------------------------
    -- Admin Workflow Audit
    -- approved_at : When admin approved the listing. NULL until approved.
    --   Displayed to tenants as "Listed since: [date]".
    --   Also used for admin KPI: average time from submission to approval.
    -- approved_by : UUID of the admin who approved. Raw UUID (not FK) to avoid
    --   JOIN on every property fetch. Admin lookup is rare and can tolerate
    --   an application-level query when needed.
    -- -------------------------------------------------------------------------
    approved_at             TIMESTAMPTZ,
    approved_by             UUID,

    -- -------------------------------------------------------------------------
    -- Standard Audit Timestamps (all UTC)
    -- created_at: Set once by @PrePersist. immutable. mirrors `updatable=false` in JPA.
    -- updated_at: Refreshed on every UPDATE by @PreUpdate.
    -- -------------------------------------------------------------------------
    created_at              TIMESTAMPTZ     NOT NULL    DEFAULT NOW(),
    updated_at              TIMESTAMPTZ     NOT NULL    DEFAULT NOW(),

    -- =========================================================================
    -- CONSTRAINTS
    -- =========================================================================

    CONSTRAINT pk_properties
        PRIMARY KEY (id),

    -- Referential integrity: owner_id must exist in users table.
    -- RESTRICT prevents deleting a user who still owns properties.
    CONSTRAINT fk_properties_owner_id
        FOREIGN KEY (owner_id) REFERENCES users (id)
        ON DELETE RESTRICT
        ON UPDATE CASCADE,

    -- Enum guard: Hibernate stores EnumType.STRING but native SQL inserts could bypass it.
    -- CHECK constraint is the last line of defence.
    CONSTRAINT chk_properties_type
        CHECK (type IN ('PG', 'FLAT', 'HOSTEL', 'STUDIO')),

    CONSTRAINT chk_properties_status
        CHECK (status IN ('PENDING_APPROVAL', 'ACTIVE', 'INACTIVE', 'REJECTED', 'DELETED')),

    CONSTRAINT chk_properties_gender_preference
        CHECK (gender_preference IN ('ANY', 'MALE_ONLY', 'FEMALE_ONLY'))

);


-- -----------------------------------------------------------------------------
-- STEP 2: Indexes
-- PostgreSQL auto-creates indexes for PRIMARY KEY. These cover common queries.
-- -----------------------------------------------------------------------------

-- Admin dashboard: "Show me all PENDING_APPROVAL listings" or "all ACTIVE listings"
-- Also used by the status state machine checks in PropertyService.
CREATE INDEX idx_properties_status
    ON properties (status);

-- Owner dashboard: "Show me MY listings"
-- Every owner's dashboard fires: SELECT * FROM properties WHERE owner_id = ?
CREATE INDEX idx_properties_owner_id
    ON properties (owner_id);

-- Tenant search: "Show me PGs only" or "Show me STUDIOs only"
CREATE INDEX idx_properties_type
    ON properties (type);

-- Tenant search: "Show me FEMALE_ONLY properties"
-- Critical filter — female tenants must be able to exclude male-only properties.
CREATE INDEX idx_properties_gender_preference
    ON properties (gender_preference);

-- Composite: "Show me all ACTIVE properties owned by user X"
-- The most common combined query from the owner's dashboard.
-- DB can use just this one index for both owner_id and status filters.
CREATE INDEX idx_properties_owner_status
    ON properties (owner_id, status);

-- Featured listings filter: "Show me featured AND ACTIVE listings for homepage"
-- Partial index: only indexes rows where is_featured = true.
-- Much smaller index than a full-column index since very few listings are featured.
CREATE INDEX idx_properties_featured_active
    ON properties (is_featured, status)
    WHERE is_featured = TRUE;


-- -----------------------------------------------------------------------------
-- STEP 3: Table and Column Comments (visible in pgAdmin, DBeaver, psql \d+)
-- Invaluable for new team members who need to understand the schema quickly.
-- -----------------------------------------------------------------------------

COMMENT ON TABLE  properties IS
    'Core listing entity. Every PG/Flat/Hostel/Studio listed on the platform. '
    'Owned by one User (OWNER role). Managed by Admins via approval workflow.';

COMMENT ON COLUMN properties.id IS
    'UUID primary key. Generated by Hibernate @UuidGenerator before INSERT. Non-sequential to prevent enumeration.';

COMMENT ON COLUMN properties.owner_id IS
    'FK to users.id. The OWNER who created and manages this listing. Immutable once set.';

COMMENT ON COLUMN properties.name IS
    'Display name of the listing visible to tenants. E.g. "Sunrise PG for Girls".';

COMMENT ON COLUMN properties.type IS
    'Accommodation type: PG | FLAT | HOSTEL | STUDIO. Drives tenant search filtering.';

COMMENT ON COLUMN properties.description IS
    'Owner-written description of the property. No length limit. Displayed on listing detail page.';

COMMENT ON COLUMN properties.status IS
    'Lifecycle state: PENDING_APPROVAL → ACTIVE or REJECTED → INACTIVE → DELETED. '
    'Soft-delete pattern: rows with DELETED are invisible but never removed.';

COMMENT ON COLUMN properties.rejection_reason IS
    'Admin-written reason when rejecting a listing. NULL unless status = REJECTED. '
    'Shown to owner so they know exactly what to fix before resubmitting.';

COMMENT ON COLUMN properties.gender_preference IS
    'Gender restriction for this accommodation: ANY | MALE_ONLY | FEMALE_ONLY. '
    'Service layer enforces this before accepting a booking from a tenant.';

COMMENT ON COLUMN properties.house_rules IS
    'Owner-defined rules. Free text. E.g. "No smoking. Guests allowed till 10 PM."';

COMMENT ON COLUMN properties.security_deposit_amount IS
    'Refundable security deposit in INR. Nullable — some owners waive this.';

COMMENT ON COLUMN properties.is_featured IS
    'Admin-only flag. Featured listings get priority placement in tenant search. '
    'Owners cannot self-feature — enforced at service layer.';

COMMENT ON COLUMN properties.approved_at IS
    'UTC timestamp when admin approved this listing. NULL until approved. '
    'Displayed as "Listed since [date]" on tenant-facing UI.';

COMMENT ON COLUMN properties.approved_by IS
    'UUID of the admin who approved. Raw UUID (not FK) to avoid JOIN overhead. '
    'Used for admin accountability audits.';

COMMENT ON COLUMN properties.created_at IS
    'UTC timestamp of first INSERT. Immutable.';

COMMENT ON COLUMN properties.updated_at IS
    'UTC timestamp of last UPDATE. Refreshed by Hibernate @PreUpdate.';
