package com.smartpg.module.property.model;

import com.smartpg.module.property.enums.GenderPreference;
import com.smartpg.module.property.enums.PropertyStatus;
import com.smartpg.module.property.enums.PropertyType;
import com.smartpg.module.user.model.User;
import jakarta.persistence.*;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;
import org.hibernate.annotations.UuidGenerator;

import java.time.Instant;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

/**
 * Core entity representing a property listing on the Smart PG platform.
 *
 * <p><b>What is this?</b>
 * A {@code Property} is the single source of truth for everything about a
 * physical accommodation space listed by an Owner. Think of it as the "listing"
 * you see on a platform like MagicBricks or NoBroker — but richer, because we
 * also track admin approval, gender policies, and house rules.
 *
 * <p><b>Separation of Concerns - Why 4 tables instead of 1?</b>
 * <ul>
 *   <li>{@code Property} - Core identity and business rules (name, type, status, policy)</li>
 *   <li>{@link PropertyAddress} - Location data (street, pincode, lat/lng). Separate
 *       because address is often updated independently, and future geo-queries
 *       (find properties within 5km) only need this table + coordinates.</li>
 *   <li>{@link PropertyPhoto} - Multiple photos per property. Using a child table
 *       (not a comma-separated URL string) lets us add ordering, captions, and
 *       cover-photo flags without hacking a String column.</li>
 *   <li>{@link PropertyAmenity} - Each amenity is a row. Lets us do
 *       "find all properties with WIFI AND AC" as a clean IN/EXISTS query
 *       instead of ugly LIKE '%WIFI%' on a text column.</li>
 * </ul>
 *
 * <p><b>Lifecycle</b>:
 * <pre>
 *   Owner POSTs /api/v1/properties
 *       -> status = PENDING_APPROVAL (auto-set)
 *   Admin reviews
 *       -> ACTIVE (live to tenants) or REJECTED (with reason)
 *   Owner deactivates
 *       -> INACTIVE (hidden from search, tenancies unaffected)
 *   Owner/Admin deletes
 *       -> DELETED (soft delete, never hard delete)
 * </pre>
 *
 * <p><b>Table</b>: {@code properties}
 */
@Entity
@Table(
    name = "properties",
    indexes = {
        // Admin dashboard: filter pending approvals
        @Index(name = "idx_properties_status",            columnList = "status"),
        // Owner dashboard: show my listings
        @Index(name = "idx_properties_owner_id",          columnList = "owner_id"),
        // Tenant search: filter by type
        @Index(name = "idx_properties_type",              columnList = "type"),
        // Tenant search: filter by gender preference
        @Index(name = "idx_properties_gender_preference", columnList = "gender_preference"),
        // Composite: owner's listings by status (most common admin + owner query)
        @Index(name = "idx_properties_owner_status",      columnList = "owner_id, status")
    }
)
@Getter
@Setter
@NoArgsConstructor
@ToString(exclude = {"owner", "address", "photos", "amenities"})
public class Property {

    // -------------------------------------------------------------------------
    // Primary Key
    // -------------------------------------------------------------------------

    /**
     * Non-sequential UUID primary key.
     * Prevents ID enumeration: a malicious user can't guess
     * valid property IDs by incrementing an integer.
     * Generated by Hibernate before INSERT - never null on a managed entity.
     */
    @Id
    @UuidGenerator
    @Column(name = "id", updatable = false, nullable = false)
    private UUID id;

    // -------------------------------------------------------------------------
    // Owner Relationship
    // -------------------------------------------------------------------------

    /**
     * The OWNER user who created and manages this property.
     *
     * <p><b>ManyToOne (not OneToOne)</b>: One owner can have MANY properties.
     * The FK column {@code owner_id} lives in THIS table (properties).
     *
     * <p>{@code FetchType.LAZY}: Loading a property for a tenant search result
     * card does NOT need the full Owner entity (name, email, password hash, etc.).
     * Lazy loading prevents that unnecessary JOIN on every property fetch.
     *
     * <p>{@code nullable = false}: A property MUST have an owner. Orphaned
     * listings are impossible at the DB level.
     *
     * <p>{@code updatable = false}: Once a property is created, its owner cannot
     * be changed. This prevents data integrity bugs (tenant's receipts would
     * reference a different owner mid-tenancy). If ownership transfer is needed,
     * it must go through a dedicated workflow with audit trail.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(
        name = "owner_id",
        nullable = false,
        updatable = false,
        foreignKey = @ForeignKey(name = "fk_properties_owner_id")
    )
    private User owner;

    // -------------------------------------------------------------------------
    // Core Identity
    // -------------------------------------------------------------------------

    /**
     * The display name of the property.
     * This is what tenants see in search results and the listing detail page.
     * Example: "Sunrise PG for Girls", "Green Valley Hostel", "Studio 42".
     * Should be unique per owner (enforced in service layer, not DB constraint).
     */
    @Column(name = "name", nullable = false, length = 255)
    private String name;

    /**
     * Type of accommodation: PG, FLAT, HOSTEL, or STUDIO.
     * Critical for tenant filtering. Stored as EnumType.STRING.
     *
     * @see PropertyType
     */
    @Enumerated(EnumType.STRING)
    @Column(name = "type", nullable = false, length = 20)
    private PropertyType type;

    /**
     * Rich text description of the property.
     * Owners use this to highlight what makes their PG special:
     * neighbourhood, ambience, nearby landmarks, rules summary.
     * Stored as TEXT (unlimited length in PostgreSQL).
     */
    @Column(name = "description", columnDefinition = "TEXT")
    private String description;

    // -------------------------------------------------------------------------
    // Lifecycle State
    // -------------------------------------------------------------------------

    /**
     * Current lifecycle state of this listing.
     * Controls visibility to tenants, editability by owner, and admin actions.
     *
     * <p>Default: PENDING_APPROVAL on creation - every listing needs admin sign-off.
     * This prevents fake/spam listings from going live instantly.
     *
     * @see PropertyStatus
     */
    @Enumerated(EnumType.STRING)
    @Column(name = "status", nullable = false, length = 20)
    private PropertyStatus status = PropertyStatus.PENDING_APPROVAL;

    /**
     * Admin-written reason for rejection.
     * Populated ONLY when status is REJECTED. Null for all other states.
     * Shown to the Owner so they know exactly what to fix before resubmitting.
     *
     * Example: "The address provided doesn't match any valid postal code in our system."
     */
    @Column(name = "rejection_reason", columnDefinition = "TEXT")
    private String rejectionReason;

    // -------------------------------------------------------------------------
    // Policies / House Rules
    // -------------------------------------------------------------------------

    /**
     * Gender restriction for this property.
     * Critical for PG accommodations in India. Tenant search MUST filter on this.
     * Stored as EnumType.STRING: "ANY", "MALE_ONLY", or "FEMALE_ONLY".
     *
     * @see GenderPreference
     */
    @Enumerated(EnumType.STRING)
    @Column(name = "gender_preference", nullable = false, length = 15)
    private GenderPreference genderPreference = GenderPreference.ANY;

    /**
     * Owner-defined house rules for tenants.
     * Free text: "No smoking. Guests allowed till 10 PM. No loud music after 9 PM."
     * Stored as TEXT. Displayed on the listing detail page and included in
     * the digital tenancy agreement.
     */
    @Column(name = "house_rules", columnDefinition = "TEXT")
    private String houseRules;

    /**
     * Security deposit amount in Indian Rupees (INR).
     * Represents how much the tenant must pay upfront as a refundable deposit.
     * Displayed on the listing and recorded in the tenancy record on booking.
     * Nullable - some owners may not charge a deposit (unusual but valid).
     */
    @Column(name = "security_deposit_amount")
    private Integer securityDepositAmount;

    /**
     * Whether this listing is featured on the homepage / top of search results.
     * Set by Admin or Super Admin only. Owners cannot self-feature.
     * Featured listings get priority placement in tenant search results.
     */
    @Column(name = "is_featured", nullable = false)
    private boolean featured = false;

    // -------------------------------------------------------------------------
    // Relationships
    // -------------------------------------------------------------------------

    /**
     * The physical address of this property.
     * One-to-One: every property has exactly one address.
     *
     * <p>{@code CascadeType.ALL}: saving a property cascades to its address.
     * No need to separately persist the address - it flows from the property.
     * {@code orphanRemoval = true}: if address is set to null, the DB row is deleted.
     * {@code LAZY}: address is only loaded when explicitly accessed.
     */
    @OneToOne(mappedBy = "property", cascade = CascadeType.ALL, orphanRemoval = true, fetch = FetchType.LAZY)
    private PropertyAddress address;

    /**
     * All photos uploaded for this property.
     * One-to-Many: a property can have multiple photos (minimum 1 required to go live).
     *
     * <p>Initialized to an empty ArrayList so callers can always do
     * {@code property.getPhotos().add(photo)} without a NullPointerException.
     * The list is never null, even before any photos are added.
     *
     * <p>{@code CascadeType.ALL}: adding a photo to this list and saving the
     * property auto-persists the photo. No separate photo.save() needed.
     * {@code orphanRemoval = true}: removing a photo from the list deletes its DB row.
     */
    @OneToMany(mappedBy = "property", cascade = CascadeType.ALL, orphanRemoval = true, fetch = FetchType.LAZY)
    @OrderBy("displayOrder ASC, createdAt ASC")
    private List<PropertyPhoto> photos = new ArrayList<>();

    /**
     * All amenities offered by this property (WIFI, AC, MEALS_PROVIDED, etc.).
     * One-to-Many: a property can list multiple amenities.
     *
     * <p>Initialized to an empty list. Amenities can be added or removed
     * (orphanRemoval deletes removed ones from DB).
     */
    @OneToMany(mappedBy = "property", cascade = CascadeType.ALL, orphanRemoval = true, fetch = FetchType.LAZY)
    private List<PropertyAmenity> amenities = new ArrayList<>();

    // -------------------------------------------------------------------------
    // Admin Workflow Timestamps
    // -------------------------------------------------------------------------

    /**
     * Timestamp when an admin approved this property.
     * Null until approved. Useful for: admin performance metrics (time-to-approval),
     * displaying "Listed since: [date]" on the tenant UI.
     */
    @Column(name = "approved_at")
    private Instant approvedAt;

    /**
     * UUID of the admin who approved this listing.
     * Stored as raw UUID (not a FK) to keep the property table free of extra JOINs.
     * Used for admin accountability: "who approved this fraudulent listing?"
     */
    @Column(name = "approved_by")
    private UUID approvedBy;

    // -------------------------------------------------------------------------
    // Audit Timestamps
    // -------------------------------------------------------------------------

    /**
     * UTC timestamp of when this property was first created (submitted by owner).
     * Set once on INSERT, never changes.
     * Why Instant? Timezone-agnostic. Stored as UTC, formatted per user's timezone at UI layer.
     */
    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    /**
     * UTC timestamp of the last modification to this property record.
     * Updated by Hibernate on every UPDATE via @PreUpdate.
     */
    @Column(name = "updated_at", nullable = false)
    private Instant updatedAt;

    // -------------------------------------------------------------------------
    // Lifecycle Hooks
    // -------------------------------------------------------------------------

    /**
     * Called by Hibernate BEFORE the first INSERT.
     * Guarantees createdAt and updatedAt are always set.
     * Even if PropertyService forgets to set them, this fires automatically.
     */
    @PrePersist
    protected void onCreate() {
        Instant now = Instant.now();
        this.createdAt = now;
        this.updatedAt = now;
    }

    /**
     * Called by Hibernate BEFORE every UPDATE.
     * Always refreshes updatedAt to the current UTC instant.
     */
    @PreUpdate
    protected void onUpdate() {
        this.updatedAt = Instant.now();
    }

    // -------------------------------------------------------------------------
    // equals & hashCode
    // -------------------------------------------------------------------------

    /**
     * Equality based solely on id.
     * Two Property objects are the same listing if they share the same UUID.
     * Handles the pre-persist null case: two new (unsaved) properties are never equal.
     */
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Property other)) return false;
        return id != null && id.equals(other.id);
    }

    /**
     * Fixed constant hashCode.
     * Intentional: a new entity (id=null) shouldn't have a changing hash.
     * Once persisted, the UUID provides identity via equals().
     */
    @Override
    public int hashCode() {
        return getClass().hashCode();
    }
}
